on:
  workflow_dispatch:
    inputs:
      steps:
        description: 'Steps to be executed'
        required: true
        default: 'all'
        type: choice
        options:
          - integration
          - all

jobs:
  integration:
    runs-on: ubuntu-latest
    if: ${{ inputs.steps == 'integration' || inputs.steps == 'all' }} 
    steps:
      - name: Print the job name
        run: echo Integration Job

  deployment:
    runs-on: ubuntu-latest
    needs: integration
    if: ${{ inputs.steps == 'all' && ( needs.integration.result == 'success' ) }} 
    steps:
      - name: Print the job name
        run: echo Deployment Job
